apiVersion: v1
kind: Pod
metadata:
  name: labelpod2
  labels:
    env: prod
    owner: Book
    bu: finance
    tier: frontend


spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 9902