apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: labelpod3
spec:
  # modify replicas according to your case
  replicas: 10
  selector:
    matchLabels:
      tier: backend
  template:
    metadata:
      labels:
    	env: prod
        tier: backend
    spec:
      containers:
      - name: nginx
        image: nginx