apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset-2
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: nginx
    spec:
      containers:
      - name: nginx
        image: mginx